name: enco
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - pandas
  - matplotlib
  - networkx
  - pydot
  - tqdm
  - graphviz
  - notebook
  - ipywidgets
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
    - gdown
